//WRITE AN ALGORITHM AND PROGRAM FOR FOLLOWING CASES IN LIST (STATIC IMPLEMENTATION)

// a. INSERTION OPERATIONS
//     i. INSERT NODE AT BEGINNING OF THE LIST
//     ii. INSERT NODE AT END OF THE LIST
//     iii. INSERT NODE AFTER SPECIFIC NODE
// b. DELETION OPERATIONS
//     i. DELETE NODE FROM BEGINNING OF THE LIST
//     ii. DELETE NODE FROM END OF THE LIST
//     iii. DELETE NODE AFTER SPECIFIC NODE

#include <iostream>
#include <conio.h>
#include <stdlib.h>
