// SINGLY LINKED LIST
// LINKED LIST:
// WRITE AN ALGORITHM AND PROGRAM FOR FOLLOWING CASES IN SINGLY LINEAR LINKED LIST:
// 1.     INSERTION OPERATIONS
// a.     INSERT NODE AT BEGINNING OF THE LIST
// b.     INSERT NODE AT END OF THE LIST
// c.      INSERT NODE AFTER SPECIFIC NODE
// d.     INSERT NODE BEFORE SPECIFIC NODE
// 2.     DELETION OPERATIONS
// a.     DELETE NODE FROM BEGINNING OF THE LIST
// b.     DELETE NODE FROM END OF THE LIST
// c.      DELETE NODE AFTER SPECIFIC NODE
// MAKE NECESSARY MODIFICATIONS IN ABOVE PROGRAM TO PERFORM OPERATIONS IN CIRCULAR LINKED LIST.